### ISSUE TITLE
@inject called with undefined this could mean that the class undefined has a circular dependency problem.

### ISSUE THREAD

**Issue by pareshjoshi** [sirixdb/sirix-web-frontend#24]
With most recent changes, I started seeing these errors in console:

```
7d8c56d89e132e2d7879.js:2 Uncaught (in promise) Error: @inject called with undefined this could mean that the class undefined has a circular dependency problem. You can use a LazyServiceIdentifer to  overcome this limitation.
    at 7d8c56d89e132e2d7879.js:2
    at 7d8c56d89e132e2d7879.js:2
    at 7d8c56d89e132e2d7879.js:2
    at Object.<anonymous> (7d8c56d89e132e2d7879.js:2)
    at o (7d8c56d89e132e2d7879.js:2)
    at Module.569 (2c4aaddaf3f9d5a3bfbb.js:1)
    at c (9a011b95eb207f07c163.js:1)
```

**Comment by pareshjoshi** [comment]
I've a fix for this error

**Comment by JohannesLichtenberger** [comment]
Can we maybe add a test environment, such that this kind of stuff gets tested via a CI/CD server? Github now provides actions for instance, but maybe you know better than me what to do...

**Comment by JohannesLichtenberger** [comment]
Such that I won't accept PRs which break something in the first place...

**Comment by pareshjoshi** [comment]
Yes, we need sanity checks run. However, given you are the owner of the repo, only you can configure webhooks or integration with some of the free build/CI systems

**Comment by JohannesLichtenberger** [comment]
I just created a team... so, if you like to be part of the team that would be great for sure :-)

**Comment by pareshjoshi** [comment]
@JohannesLichtenberger  - Yes, please. Do add me. I will try and setup CI to build app and run tests.

**Comment by JohannesLichtenberger** [comment]
You have an invite, great that you're onboard :-)
