### ISSUE TITLE
TableView / Change the JavaScript code to TypeScript code

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix-web-frontend#3]
We need to change the example JavaScript code to TypeScript code and then start work on getting the data from a running HTTP-Server via the Axios HTTP-Client for instance.

**Comment by oznakn** [comment]
If you mean migrating the file https://github.com/sirixdb/sirix-web-frontend/blob/master/src/views/TableView.vue from javascript to typescript, I can take it if it is okey for you.

**Comment by JohannesLichtenberger** [comment]
Yes, amazing :-) Thank you so much! I'm super new to the frontend dev sadly. So, I now first want to make myself a bit familiar with TypeScript... and I just struggled a bit with changing the code.

**Comment by JohannesLichtenberger** [comment]
Oh BTW would you recommend switching to Nuxt.js instead of "pure" Vue.js and Typescript?

**Comment by oznakn** [comment]
Actually, no. Nuxt.js is one of the amazing SSR frameworks but Vue.js is designed to be a client side rendering framework. For small apps yes, nuxt.js is awesome, but when the apps are starting to getting bigger, problems can occur. If you have thoughts about SEO, I can recommend you prerender.io, it is a very nice service for client side rendering frameworks.

**Comment by JohannesLichtenberger** [comment]
Ah thanks, but you should be able to open a specific database in the future, which needs OpenID-connect / authentication with Keycloak. Think of it as a front-end for a DBMS like MongoDB or PostgreSQL :-) so, no SEO required luckily.

**Comment by JohannesLichtenberger** [comment]
I mean SirixDB in comparison is a very lightweight database backend (also embeddable as a Java library), which implements versioning aspects at its core, to retain the version history of the resources.

**Comment by oznakn** [comment]
Wow, thats interesting, then maybe Nuxt can be used for this situation, probably some research needed.

**Comment by JohannesLichtenberger** [comment]
Hm, but I think the whole project might grow over time and I'd love to include interactive D3.js visualizations in order to compare very big resources (XML or JSON) stored in a binary encoding. Certainly we can only query for the interesting fragments using more or less XQuery (Basically more or less JSONiq) to query both database types. However, there's plenty of optimization potential in rewriting queries to use user defined index-structures and a lot of statistical stuff which SirixDB stores.

**Comment by JohannesLichtenberger** [comment]
Guess endless possibilities to work on as always regarding SirixDB ;-)

**Comment by JohannesLichtenberger** [comment]
https://dev.to/johanneslichtenberger/help-with-maven-multi-module-project-java-module-system-with-a-pr-3ifi
