### ISSUE TITLE
Vue.js Auth Component

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix-web-frontend#31]
We need a component, which extracts the code from the redirected to URL (from the OAuth2 auth code flow) and exchange this code with a token (`/token`) endpoint on the SirixDB HTTP-Server. This token then needs to be sent in subsequent requests, so we can probably store it in the store!?

**Comment by JohannesLichtenberger** [comment]
[Here's how to setup](https://sirix.io/rest-api.html) a running backend SirixDB HTTP-Server together with Keycloak.

**Comment by JohannesLichtenberger** [comment]
In Keycloak you have to change the authentication mode to Authorization Code Flow and in the `sirix-conf.json` file, too (`oAuthFlowType` must be `AUTH_CODE`) and you have to specify where Keycloak redirddcts to after the authentication code is generated (afterwards this code has to be used to retrieve the token from the `POST /token` route): https://github.com/sirixdb/sirix/pull/120

**Comment by JohannesLichtenberger** [comment]
@robsontenorio can you help?

**Comment by robsontenorio** [comment]
Hi, I am sorry, but the PR was not merged. Just use a custom plugin I wrote myself. You can give a try 

https://gist.github.com/robsontenorio/d1e56c5bc5bc391ba0791be77419a68c

**Comment by JohannesLichtenberger** [comment]
What I'm currently doing is:

1. If 401 HTTP response is sent from the server then
2. Redirect to /login endpoint/page.
3. This page has a simple button which does a `GET request` against `/user/authorize` whereas the Vert.x based Server redirects to Keycloak for the login form (302 HTTP code with a location header)
4. The user puts in valid username/password and gets redirected to the Node.js server (`http://127.0.0.1/callback`)
5. On this callback page Nuxt.js would have to extract the `code` parameter and send it to the `/token` endpoint on the Vert.x server
6. The response contains the JWT token.
7. It must be stored somewhere such that it is sent with each request in the Authorization header as a `Bearer` token.

I don't want to use cookies and sessions as it doesn't scale and is not RESTful.

However after fixing some Docker networking issues I'm still at point 3. It seems Axios per default is following redirects. But I'm getting this cross site origin not allowed (CORS) error in Chrome when Axios wants to retrieve the Keycloak Login page. I've put http://127.0.0.1:3005 as the URL for allowed Web Origins, but it doesn't work. Even a * doesn't work. And somehow setting the Origin Header is not allowed in Chrome.

I'm very new to the front-end and middleware stuff, so I don't know what's wrong.

And your plugin extracts the code fragedmt and does a POST to thed token endpoint?

My Nuxt.js.conf (relevant parts):

```json
axios: {
    baseURL: 'https://127.0.0.1:9443',
    browserBaseURL: 'https://127.0.0.1:9443',
    headers: {
      'Access-Control-Allow-Origin': '*',
    },
    proxyHeaders: true,
    proxy: true,
  },
  auth: {
    strategies: {
      social: {
        _scheme: 'oauth2',
        authorization_endpoint: '/user/authorize',
        userinfo_endpoint: false,
        scope: ['create','view','modify','delete'],
        access_type: 'offline',
        access_token_endpoint: '/token',
        response_type: 'code',
        token_type: 'Bearer',
        redirect_uri: '/',
        client_id: 'sirix',
        token_key: 'access_token',
        state: 'UNIQUE_AND_NON_GUESSABLE'
      }
    }
  },
  router: {
    middleware: ['auth']
  },
```

And the login page simply: https://github.com/sirixdb/sirix-web-frontend/blob/oauth2-auth/pages/login/index.vue

And Axios slightly extended:
https://github.com/sirixdb/sirix-web-frontend/blob/oauth2-auth/plugins/axios.js

**Comment by JohannesLichtenberger** [comment]
@robsontenorio Did you have a problem with CORS?

Keycloak somehow isn't writing the appropriate HTTP-Headers:
https://keycloak.discourse.group/t/access-control-allow-origin-header-missing/328/9?u=johannes
